"""facts and derived answers

Revision ID: 26ebb6747b04
Revises: 35bfd8ff4f95
Create Date: 2026-09-03 22:52:20.803534

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26ebb6747b04"
down_revision: str | Sequence[str] | None = "35bfd8ff4f95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "work_rights",
                "licence",
                "checks",
                "education",
                "experience",
                "availability",
                "compensation",
                "transport",
                "referees",
                "health",
                "business",
                "other",
                name="factcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("jurisdiction", sa.Enum("AU", "NZ", name="region"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_fact_key"),
    )
    with op.batch_alter_table("fact", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fact_key"), ["key"], unique=False)

    op.create_table(
        "derived_answer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("answer_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "answer_type",
            sa.Enum(
                "text",
                "boolean",
                "choice",
                "number",
                "date",
                name="answertype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("fact_id", sa.Integer(), nullable=True),
        sa.Column("fact_text_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region", sa.Enum("AU", "NZ", name="region"), nullable=True),
        sa.Column("reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["fact_id"], ["fact.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "question_key", "region", name="uq_derived_answer_question_region"
        ),
    )
    with op.batch_alter_table("derived_answer", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_derived_answer_fact_id"), ["fact_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_derived_answer_question_key"), ["question_key"], unique=False
        )

    with op.batch_alter_table("answer_bank", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fact_category",
                sa.Enum(
                    "work_rights",
                    "licence",
                    "checks",
                    "education",
                    "experience",
                    "availability",
                    "compensation",
                    "transport",
                    "referees",
                    "health",
                    "business",
                    "other",
                    name="factcategory",
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer_bank", schema=None) as batch_op:
        batch_op.drop_column("fact_category")

    with op.batch_alter_table("derived_answer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_derived_answer_question_key"))
        batch_op.drop_index(batch_op.f("ix_derived_answer_fact_id"))

    op.drop_table("derived_answer")
    with op.batch_alter_table("fact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_key"))

    op.drop_table("fact")
    # ### end Alembic commands ###
