"""initial schema

Revision ID: 2c01ae3b59ac
Revises:
Create Date: 2026-08-23 14:12:38.499065

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c01ae3b59ac"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("search_terms", sa.JSON(), nullable=False),
        sa.Column("locations", sa.JSON(), nullable=False),
        sa.Column("salary_floor", sa.Integer(), nullable=True),
        sa.Column("work_types", sa.JSON(), nullable=False),
        sa.Column("exclusions", sa.JSON(), nullable=False),
        sa.Column("score_floor", sa.Float(), nullable=False),
        sa.Column("score_auto_apply", sa.Float(), nullable=False),
        sa.Column(
            "gray_zone_action",
            sa.Enum(
                "apply",
                "skip",
                "ask",
                "queue",
                name="grayzoneaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("daily_caps", sa.JSON(), nullable=False),
        sa.Column(
            "target_goal_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("target_goal_count", sa.Integer(), nullable=True),
        sa.Column("template_ids", sa.JSON(), nullable=False),
        sa.Column("rubric", sa.JSON(), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "form_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("platform", "company", name="formmaptier", native_enum=False),
            nullable=False,
        ),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_form_map_fingerprint"),
    )
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("identity", sa.JSON(), nullable=False),
        sa.Column("work_rights", sa.JSON(), nullable=False),
        sa.Column("experience", sa.JSON(), nullable=False),
        sa.Column("projects", sa.JSON(), nullable=False),
        sa.Column("education", sa.JSON(), nullable=False),
        sa.Column("certifications", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version", name="uq_profile_version"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column(
            "phase",
            sa.Enum(
                "discovery",
                "scoring",
                "documents",
                "apply",
                "email",
                "maintenance",
                name="runphase",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer_bank",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "question_pattern", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "match_type",
            sa.Enum("exact", "regex", "fuzzy", name="matchtype", native_enum=False),
            nullable=False,
        ),
        sa.Column("answer_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "answer_type",
            sa.Enum(
                "text",
                "boolean",
                "choice",
                "number",
                "date",
                name="answertype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("choices", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("answer_bank", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_answer_bank_campaign_id"), ["campaign_id"], unique=False
        )

    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.Column("dedupe_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "apply_type",
            sa.Enum(
                "quick_apply",
                "easy_apply",
                "external",
                "unknown",
                "manual_only",
                name="applytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "ad_contact_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "scored",
                "rejected",
                "queued",
                "documents_ready",
                "needs_answer",
                "applying",
                "applied",
                "failed",
                "manual_queue",
                "skipped",
                "ghosted",
                name="jobstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "source_job_id", name="uq_job_source_source_job_id"
        ),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index("ix_job_dedupe_hash", ["dedupe_hash"], unique=False)
        batch_op.create_index("ix_job_status", ["status"], unique=False)

    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "resume",
                "cover_letter",
                "email",
                name="templatekind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_template_campaign_id"), ["campaign_id"], unique=False
        )

    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "resume",
                "cover_letter",
                "combined",
                name="documentkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parse_check_passed", sa.Boolean(), nullable=False),
        sa.Column("parse_report", sa.JSON(), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=True),
        sa.Column("built_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_job_id"), ["job_id"], unique=False
        )

    op.create_table(
        "llm_spend",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("called_at", sa.DateTime(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_spend", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_spend_job_id"), ["job_id"], unique=False
        )

    op.create_table(
        "score",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("stage1", sa.Float(), nullable=True),
        sa.Column("stage2", sa.Float(), nullable=True),
        sa.Column("final", sa.Float(), nullable=True),
        sa.Column("reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("matched_skills", sa.JSON(), nullable=False),
        sa.Column("gaps", sa.JSON(), nullable=False),
        sa.Column("red_flags", sa.JSON(), nullable=False),
        sa.Column("scored_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id",
            "profile_version",
            "rubric_version",
            name="uq_score_job_profile_rubric",
        ),
    )
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("resume_doc_id", sa.Integer(), nullable=True),
        sa.Column("cover_letter_doc_id", sa.Integer(), nullable=True),
        sa.Column(
            "attachment_readback", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("answers_given", sa.JSON(), nullable=False),
        sa.Column("screenshot_pre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("screenshot_post", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "submitted",
                "failed",
                "aborted",
                name="applicationoutcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "response_status",
            sa.Enum(
                "none",
                "acknowledged",
                "rejected",
                "interview_request",
                "recruiter_outreach",
                "ghosted",
                name="responsestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("response_at", sa.DateTime(), nullable=True),
        sa.Column("user_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cover_letter_doc_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_doc_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", name="uq_application_job_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application")
    op.drop_table("score")
    with op.batch_alter_table("llm_spend", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_spend_job_id"))

    op.drop_table("llm_spend")
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_job_id"))

    op.drop_table("document")
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_template_campaign_id"))

    op.drop_table("template")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_status")
        batch_op.drop_index("ix_job_dedupe_hash")
        batch_op.drop_index(batch_op.f("ix_job_campaign_id"))

    op.drop_table("job")
    with op.batch_alter_table("answer_bank", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answer_bank_campaign_id"))

    op.drop_table("answer_bank")
    op.drop_table("run")
    op.drop_table("profile")
    op.drop_table("form_map")
    op.drop_table("campaign")
    # ### end Alembic commands ###
