"""score rubric hash

Revision ID: 35bfd8ff4f95
Revises: e45ebd3c60f7
Create Date: 2026-09-03 02:42:52.716430

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35bfd8ff4f95"
down_revision: str | Sequence[str] | None = "e45ebd3c60f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("rubric_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.drop_column("rubric_hash")

    # ### end Alembic commands ###
