"""preference table

Revision ID: 499ea1ebf50e
Revises: d7ed910db969
Create Date: 2026-09-03 02:11:07.183049

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "499ea1ebf50e"
down_revision: str | Sequence[str] | None = "d7ed910db969"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum(
                "text",
                "boolean",
                "choice",
                "number",
                "date",
                name="answertype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.Enum("global", "campaign", name="preferencescope", native_enum=False),
            nullable=False,
        ),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "user_set",
                "asked",
                "inferred",
                name="preferencesource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "proposed",
                "rejected",
                "retired",
                name="preferencestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("times_confirmed", sa.Integer(), nullable=False),
        sa.Column("times_ignored", sa.Integer(), nullable=False),
        sa.Column("evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("learned_at", sa.DateTime(), nullable=False),
        sa.Column("last_asked_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "campaign_id", name="uq_preference_key_scope"),
    )
    with op.batch_alter_table("preference", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_preference_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_preference_key"), ["key"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_preference_key"))
        batch_op.drop_index(batch_op.f("ix_preference_campaign_id"))

    op.drop_table("preference")
    # ### end Alembic commands ###
