"""job carries the options its parked question offered

Revision ID: 69618fa3f706
Revises: c2cfcf8fc987
Create Date: 2026-09-06 02:58:59.256476

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.


# revision identifiers, used by Alembic.
revision: str = "69618fa3f706"
down_revision: str | Sequence[str] | None = "c2cfcf8fc987"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("needs_answer_choices", sa.JSON(none_as_null=True), nullable=True)
        )
        # server_default, not just a Python default: the column is NOT NULL and
        # the table already has rows, which SQLite's table rebuild would leave
        # NULL. The default is dropped from the model's own DDL going forward —
        # it exists to fill in what is already there.
        batch_op.add_column(
            sa.Column(
                "needs_answer_multi",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_column("needs_answer_multi")
        batch_op.drop_column("needs_answer_choices")

    # ### end Alembic commands ###
