"""session health

Revision ID: 6f391aa66524
Revises: 26ebb6747b04
Create Date: 2026-09-03 23:08:09.458040

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f391aa66524"
down_revision: str | Sequence[str] | None = "26ebb6747b04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "live",
                "dead",
                "unknown",
                "no_session",
                "unreachable",
                name="sessionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cookie_count", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site", name="uq_session_health_site"),
    )
    with op.batch_alter_table("session_health", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_session_health_site"), ["site"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_health", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_health_site"))

    op.drop_table("session_health")
    # ### end Alembic commands ###
