"""outbound message

Revision ID: 73d8f0e11f6d
Revises: a6e45efad6dc
Create Date: 2026-09-05 15:41:13.703478

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73d8f0e11f6d"
down_revision: str | Sequence[str] | None = "a6e45efad6dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("to_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "drafted", "sent", "skipped", name="outboundstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("approved_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", name="uq_outbound_message_job"),
    )
    with op.batch_alter_table("outbound_message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_outbound_message_job_id"), ["job_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbound_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbound_message_job_id"))

    op.drop_table("outbound_message")
    # ### end Alembic commands ###
