"""score requirements

Revision ID: a6e45efad6dc
Revises: 6f391aa66524
Create Date: 2026-09-03 23:17:52.363985

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.


# revision identifiers, used by Alembic.
revision: str = "a6e45efad6dc"
down_revision: str | Sequence[str] | None = "6f391aa66524"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.add_column(sa.Column("requirements", sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.drop_column("requirements")

    # ### end Alembic commands ###
