"""stage timing and cache event

Revision ID: c2cfcf8fc987
Revises: fc81d3f8d9b3
Create Date: 2026-09-05 22:00:26.944044

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2cfcf8fc987"
down_revision: str | Sequence[str] | None = "fc81d3f8d9b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "cache",
            sa.Enum(
                "form_map",
                "site_knowledge",
                "embedding",
                name="cachename",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("hit", sa.Boolean(), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cache_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cache_event_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cache_event_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cache_event_platform"), ["platform"], unique=False
        )

    op.create_table(
        "stage_timing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "page_load",
                "field_enumeration",
                "answer_resolution",
                "document_build",
                "upload",
                "submit",
                "pacing",
                name="stage",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stage_timing", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stage_timing_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stage_timing_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stage_timing_platform"), ["platform"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stage_timing", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stage_timing_platform"))
        batch_op.drop_index(batch_op.f("ix_stage_timing_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_stage_timing_job_id"))

    op.drop_table("stage_timing")
    with op.batch_alter_table("cache_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cache_event_platform"))
        batch_op.drop_index(batch_op.f("ix_cache_event_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_cache_event_job_id"))

    op.drop_table("cache_event")
    # ### end Alembic commands ###
