"""failure_event ledger

Revision ID: d7ed910db969
Revises: 11c09d52282c
Create Date: 2026-09-03 02:06:06.172421

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7ed910db969"
down_revision: str | Sequence[str] | None = "11c09d52282c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failure_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "failure_type",
            sa.Enum(
                "selector_drift",
                "element_unresolved",
                "answer_abstained",
                "parse_gate",
                "readback_mismatch",
                "submit_failed",
                "source_unavailable",
                name="failuretype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("element_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("flow_variant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("failure_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_failure_event_company"), ["company"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_failure_event_element_id"), ["element_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_failure_event_flow_variant"), ["flow_variant"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_failure_event_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_failure_event_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_failure_event_platform"), ["platform"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("failure_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_failure_event_platform"))
        batch_op.drop_index(batch_op.f("ix_failure_event_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_failure_event_job_id"))
        batch_op.drop_index(batch_op.f("ix_failure_event_flow_variant"))
        batch_op.drop_index(batch_op.f("ix_failure_event_element_id"))
        batch_op.drop_index(batch_op.f("ix_failure_event_company"))

    op.drop_table("failure_event")
    # ### end Alembic commands ###
