"""region on campaign job and answer bank

Revision ID: e45ebd3c60f7
Revises: 499ea1ebf50e
Create Date: 2026-09-03 02:21:14.842566

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e45ebd3c60f7"
down_revision: str | Sequence[str] | None = "499ea1ebf50e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answer_bank", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("region", sa.Enum("AU", "NZ", name="region"), nullable=True)
        )

    # server_default="AU" on both: a NOT NULL column cannot be added to a table
    # that already has rows without one, and every row that exists predates the
    # NZ work, so AU is not a guess — it is what those rows actually are.
    #
    # It stays on the column rather than being dropped afterwards. SQLite
    # rewrites the table for any ALTER, so removing it costs a second full
    # rebuild to delete a default that is also the correct one for a row
    # inserted by older code during a rollback.
    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "region",
                sa.Enum("AU", "NZ", name="region", native_enum=False),
                nullable=False,
                server_default="AU",
            )
        )

    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "region",
                sa.Enum("AU", "NZ", name="region", native_enum=False),
                nullable=False,
                server_default="AU",
            )
        )
        batch_op.add_column(
            sa.Column(
                "salary_currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_column("salary_currency")
        batch_op.drop_column("region")

    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.drop_column("region")

    with op.batch_alter_table("answer_bank", schema=None) as batch_op:
        batch_op.drop_column("region")

    # ### end Alembic commands ###
