"""question event ledger

Revision ID: fc81d3f8d9b3
Revises: 73d8f0e11f6d
Create Date: 2026-09-05 21:35:33.553052

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps `str` to sqlmodel.sql.sqltypes.AutoString, and autogenerate
# renders columns by that fully-qualified name, so without this import a
# generated revision dies at import time with NameError. Emitted for every
# revision; the ruff post-write hook in alembic.ini drops it again on the ones
# that turn out not to reference sqlmodel at all.
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc81d3f8d9b3"
down_revision: str | Sequence[str] | None = "73d8f0e11f6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "resolution",
            sa.Enum(
                "bank",
                "fact",
                "form_map",
                "abstained",
                name="questionresolution",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_row_id", sa.Integer(), nullable=True),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_event_company"), ["company"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_event_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_event_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_event_platform"), ["platform"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_event_question"), ["question"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_event_question"))
        batch_op.drop_index(batch_op.f("ix_question_event_platform"))
        batch_op.drop_index(batch_op.f("ix_question_event_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_question_event_job_id"))
        batch_op.drop_index(batch_op.f("ix_question_event_company"))

    op.drop_table("question_event")
    # ### end Alembic commands ###
